alias kafka-logs="ssh vdl@192.168.1.40 tail -f /opt/vdl/kafka/kafka.out"
alias almdor="ssh almdor.no-ip.org"
alias almplay="mplayer http://almdor.no-ip.org:51234"
alias ber="bundle exec rake"
alias be="bundle exec"
